# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - apimariannedocker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://apimariannedocker.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_aa38cbf87d5a49f5800958b91226f0cf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f62834bae40f4835989254ca9468e131 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: apimariannedocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aa38cbf87d5a49f5800958b91226f0cf }}/apimariannedocker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'apimariannedocker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_92b5017ba0164ae49d54c3b1dae414e6 }}
        images: 'apimariannedocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aa38cbf87d5a49f5800958b91226f0cf }}/apimariannedocker:${{ github.sha }}'